version: 1.0.0

services:
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - 3000:3000
    networks:
      - node-network

  user-service:
    container_name: user-service
    build: ./user-service
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  postgres-data:
  mysql-data:
  redis-data:
